# Generated by Django 4.2.4 on 2023-08-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_product_name_alter_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="slug-auto-filled", unique=True),
        ),
    ]
