# Generated by Django 4.2.4 on 2023-08-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.FileField(upload_to=""),
        ),
    ]
