# Generated by Django 4.2.4 on 2023-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_customer_orderitem_shippingaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
