# Generated by Django 4.2.4 on 2023-09-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_productimage_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
